# Generated by Django 4.2.11 on 2024-04-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="description",
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
