# Generated by Django 4.2.11 on 2024-04-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_videos_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
