# Generated by Django 4.2.11 on 2024-04-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_alter_videos_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Videos",
            new_name="Video",
        ),
        migrations.CreateModel(
            name="VideoProxy",
            fields=[],
            options={
                "verbose_name": "published videos",
                "verbose_name_plural": "published videos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("videos.video",),
        ),
    ]
