# Generated by Django 4.2.11 on 2024-04-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_rename_videos_video_videoproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
