# Generated by Django 4.2.11 on 2024-04-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_video_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videoproxy",
            options={
                "verbose_name": "published video",
                "verbose_name_plural": "published videos",
            },
        ),
        migrations.AddField(
            model_name="video",
            name="state",
            field=models.CharField(
                choices=[("PU", "Publish"), ("DR", "Draft")], default="DR", max_length=2
            ),
        ),
    ]
