# Generated by Django 4.2.11 on 2024-04-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0006_alter_videoproxy_options_video_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="publish_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
