# Generated by Django 5.0.2 on 2024-04-09 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0007_video_publish_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="video",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
