# Generated by Django 5.0.2 on 2024-04-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0008_video_timestamp_video_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
