# Generated by Django 5.0.2 on 2024-04-09 09:38

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0009_alter_video_video_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="video",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
