# Generated by Django 5.0.2 on 2024-04-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0010_alter_video_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="video",
            managers=[],
        ),
    ]
