# Generated by Django 5.0.2 on 2024-04-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0001_initial"),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlist_videos",
                to="videos.video",
            ),
        ),
    ]
